# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.cache/wt [current_project]
set_property parent.project_path /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/hdl/ARTY_firmware_wrapper.v
add_files /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ARTY_firmware.bd
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_clk_wiz_0_0/ARTY_firmware_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_clk_wiz_0_0/ARTY_firmware_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_clk_wiz_0_0/ARTY_firmware_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_mig_7series_0_0/ARTY_firmware_mig_7series_0_0/user_design/constraints/ARTY_firmware_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_mig_7series_0_0/ARTY_firmware_mig_7series_0_0/user_design/constraints/ARTY_firmware_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_mig_7series_0_0/ARTY_firmware_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_microblaze_0_0/ARTY_firmware_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_microblaze_0_0/ARTY_firmware_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_microblaze_0_0/ARTY_firmware_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_mdm_1_0/ARTY_firmware_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_mdm_1_0/ARTY_firmware_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_rst_mig_7series_0_83M_0/ARTY_firmware_rst_mig_7series_0_83M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_rst_mig_7series_0_83M_0/ARTY_firmware_rst_mig_7series_0_83M_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_rst_mig_7series_0_83M_0/ARTY_firmware_rst_mig_7series_0_83M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_quad_spi_0_0/ARTY_firmware_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_quad_spi_0_0/ARTY_firmware_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_quad_spi_0_0/ARTY_firmware_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_quad_spi_0_0/ARTY_firmware_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_gpio_0_0/ARTY_firmware_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_gpio_0_0/ARTY_firmware_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_gpio_0_0/ARTY_firmware_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_uartlite_0_0/ARTY_firmware_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_uartlite_0_0/ARTY_firmware_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_uartlite_0_0/ARTY_firmware_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_timer_0_0/ARTY_firmware_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_timer_0_0/ARTY_firmware_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_10/bd_469f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_19/bd_469f_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_22/bd_469f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_23/bd_469f_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_24/bd_469f_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_25/bd_469f_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_26/bd_469f_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_27/bd_469f_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_20/bd_469f_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_21/bd_469f_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_11/bd_469f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_12/bd_469f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_13/bd_469f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_14/bd_469f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_15/bd_469f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_2/bd_469f_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_3/bd_469f_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_4/bd_469f_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_5/bd_469f_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_6/bd_469f_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_1/bd_469f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/bd_0/ip/ip_1/bd_469f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_xbar_0/ARTY_firmware_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_ilmb_v10_0/ARTY_firmware_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_ilmb_v10_0/ARTY_firmware_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_bram_if_cntlr_0/ARTY_firmware_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_ilmb_bram_if_cntlr_0/ARTY_firmware_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_lmb_bram_0/ARTY_firmware_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ARTY_firmware_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/constrs_1/new/ARTY_firmware.xdc
set_property used_in_implementation false [get_files /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/constrs_1/new/ARTY_firmware.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ARTY_firmware_wrapper -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ARTY_firmware_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ARTY_firmware_wrapper_utilization_synth.rpt -pb ARTY_firmware_wrapper_utilization_synth.pb"
