# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ARTY_firmware.xdc

# Block Designs: bd/ARTY_firmware/ARTY_firmware.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware || ORIG_REF_NAME==ARTY_firmware} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_clk_wiz_0_0/ARTY_firmware_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_clk_wiz_0_0 || ORIG_REF_NAME==ARTY_firmware_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_mig_7series_0_0/ARTY_firmware_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_mig_7series_0_0 || ORIG_REF_NAME==ARTY_firmware_mig_7series_0_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_microblaze_0_0/ARTY_firmware_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_microblaze_0_0 || ORIG_REF_NAME==ARTY_firmware_microblaze_0_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_mdm_1_0/ARTY_firmware_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_mdm_1_0 || ORIG_REF_NAME==ARTY_firmware_mdm_1_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_rst_mig_7series_0_83M_0/ARTY_firmware_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==ARTY_firmware_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_axi_quad_spi_0_0/ARTY_firmware_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_axi_quad_spi_0_0 || ORIG_REF_NAME==ARTY_firmware_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_axi_gpio_0_0/ARTY_firmware_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_axi_gpio_0_0 || ORIG_REF_NAME==ARTY_firmware_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_axi_uartlite_0_0/ARTY_firmware_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_axi_uartlite_0_0 || ORIG_REF_NAME==ARTY_firmware_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_axi_timer_0_0/ARTY_firmware_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_axi_timer_0_0 || ORIG_REF_NAME==ARTY_firmware_axi_timer_0_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_axi_smc_0/ARTY_firmware_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_axi_smc_0 || ORIG_REF_NAME==ARTY_firmware_axi_smc_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_microblaze_0_axi_periph_0/ARTY_firmware_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ARTY_firmware_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_xbar_0/ARTY_firmware_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_xbar_0 || ORIG_REF_NAME==ARTY_firmware_xbar_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_dlmb_v10_0 || ORIG_REF_NAME==ARTY_firmware_dlmb_v10_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_ilmb_v10_0/ARTY_firmware_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_ilmb_v10_0 || ORIG_REF_NAME==ARTY_firmware_ilmb_v10_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_dlmb_bram_if_cntlr_0/ARTY_firmware_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ARTY_firmware_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_ilmb_bram_if_cntlr_0/ARTY_firmware_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ARTY_firmware_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ARTY_firmware/ip/ARTY_firmware_lmb_bram_0/ARTY_firmware_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARTY_firmware_lmb_bram_0 || ORIG_REF_NAME==ARTY_firmware_lmb_bram_0} -quiet] -quiet

# XDC: bd/ARTY_firmware/ARTY_firmware_ooc.xdc
