# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0.xci
# IP: The module: 'ARTY_firmware_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_firmware_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_firmware_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0.xci
# IP: The module: 'ARTY_firmware_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_firmware_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/daq/Xilinx/ARTY_firmware/ARTY_firmware.srcs/sources_1/bd/ARTY_firmware/ip/ARTY_firmware_dlmb_v10_0/ARTY_firmware_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ARTY_firmware_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
